auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  aws:
    s3: poc-loki-152248006875-ap-northeast-1
    endpoint: s3.ap-northeast-1.amazonaws.com
    region: ap-northeast-1

schema_config:
  configs:
  - from: "2025-11-01"
    store: tsdb
    object_store: aws
    schema: v13
    index:
      prefix: index_
      period: 24h

limits_config:
  volume_enabled: true # 用於流量控制
  allow_structured_metadata: true # 允許在 log 中附加 structured metadata
  retention_period: 336h # 2 weeks
  # retention_period: 744h # 31 days
  # retention_period: 2160h  # 3 months

compactor:
  retention_enabled: true
  working_directory: /loki/compactor # k8s 用 emptyDir; docker 建議 volume
  compaction_interval: 10m
  delete_request_store: aws

analytics:
  reporting_enabled: false
