apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-grafana
  namespace: ob
  annotations:
    alb.ingress.kubernetes.io/group.name: 'ob'
    alb.ingress.kubernetes.io/group.order: '10'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:__YOUR_REGION__:__YOUR_AWS_ACCOUNT__:certificate/__CERTIFICATE_ID__'
spec:
  ingressClassName: 'alb'
  rules:
  - host: grafana.tonychoucc.com
    http:
      paths:
      - path: '/'
        pathType: Prefix
        backend:
          service:
            name: my-grafana
            port:
              number: 80
